id: P010597
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W26082
  title: གསང་སྙིང་སྤྱི་དོན་རྣམ་འབྱེད་རིན་ཆེན་མཛོད་ཀྱི་ལྡེ་མིག
  author: ''
  volumes:
    7cf39fbba1314d39b3d3454ca4cfdec0:
      image_group_id: I1KG12819
      title: ''
      volume_number: 1
      total_pages: 380
      base_file: v001.txt
