id: I9C4505C7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T06:30:46+00:00'
last_modified: '2022-06-08T16:08:06.630373+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W26082
  title: གསང་སྙིང་སྤྱི་དོན་རྣམ་འབྱེད་རིན་ཆེན་མཛོད་ཀྱི་ལྡེ་མིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    46FF:
      image_group_id: I1KG12819
      title: ''
      total_pages: 380
      order: 1
      base_file: 46FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
