id: I9C4505C7
legacy_id: P010597
ocr_import_info:
  bdrc_scan_id: W26082
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T06:28:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:32:31.458409+00:00'
last_modified: 2022-09-02 14:32:42.039839
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W26082
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW26082
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསང་སྙིང་སྤྱི་དོན་རྣམ་འབྱེད་རིན་ཆེན་མཛོད་ཀྱི་ལྡེ་མིག
  author: རྡོ་གྲུབ་ཆེན ༠༣་འཇིགས་མེད་བསྟན་པའི་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.7245967567605921
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I1KG12819:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12819
      total_pages: 380
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12819.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7245967567605921
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
